server:
  port: 8004

# 服务名称
spring:
  application:
    name: cloud-payment-service
  # 数据库配置
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/study?useSSL=false&useUnicode=true&characterEncoding=UTF-8&serverTimezone=GMT%2B8
    username: fuzheng
    password: heiyuyinshi
  cloud:
    zookeeper:
      connect-string: 172.17.143.133:2181

mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: weichai,fuzheng.springcloud.entities #所有entity别名类所在包
