server:
  port: 3344

spring:
  application:
    name: cloud-config-center
  cloud:
    config:
      server:
        git:
          uri: https://github.com/heiyuyinshi/spider.git # github中git仓库的名字
          search-paths:
            - spider
          username: heiyuyinshi # github账户
          password: fz8023koukai # github密码
          skipSslValidation: true
      label: master # 读取分支
  # rabbitmq相关配置
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest

eureka:
  client:
    service-url:
      defaultZone: http://localhost:7001/eureka
# 暴露bus-refresh
management:
  endpoints:
    web:
      exposure:
        include: 'bus-refresh'
